version: '3'
services:
    this_jupyter:
        build: docker/jupyter
        ports:
          - 8888:8888
        volumes:
          - .:/home/jovyan
    this_mongo:
        image: mongo
        volumes:
          - mongo_data:/data/db
volumes:
  mongo_data:
